name: Library Test/Release

on:
  push:
    tags:
      - "v*"

concurrency: release

jobs:
  qa-tag:
    name: Call QA
    uses: ./.github/workflows/test.yml

  release:
    needs: qa-tag
    name: Publish
    runs-on: ubuntu-22.04
    concurrency: publish
    env:
      # renovate: datasource=docker depName=node versioning=node
      NODE_VERSION: "20.14.0"
    permissions:
      contents: write
      id-token: write
      packages: write
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Select NodeJS version
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org

      - name: Enable Corepack
        run: corepack enable

      - name: Load cached dependencies
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-node${{ env.NODE_VERSION }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Rebuild package structure
        run: .scripts/rebuild-package-structure.sh

      - name: Determine release version
        run: echo "RELEASE_VERSION=$(node .scripts/manifest-version.cjs)" >> $GITHUB_ENV

      - name: Release new library version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd dist-area
          npm publish --access=public --provenance --tag=latest

      - name: Generate SBOM
        uses: anchore/sbom-action@e8d2a6937ecead383dfe75190d104edd1f9c5751 # v0
        with:
          format: spdx-json
          output-file: sbom.spdx.json
          upload-artifact: false
          upload-release-assets: false

      - name: Generate GitHub release
        uses: oliversalzburg/action-automatic-semantic-releases@bc429dc1af8c036b5f8c11fef7bcb0becfd5064d # v0.0.13
        with:
          body_prefix: |
            Published at <https://www.npmjs.com/package/@oliversalzburg/js-utils/v/${{ env.RELEASE_VERSION }}>.
          draft: false
          files: sbom.spdx.json
          prerelease: false
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: v${{ env.RELEASE_VERSION }}

  docs-deploy:
    name: Call Deployment
    needs: qa-tag
    permissions:
      contents: read
      id-token: write
      pages: write
    uses: ./.github/workflows/docs-deploy.yml
