name: Pre-Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: pre-release

jobs:
  qa-main:
    name: 🔹 QA
    uses: oliversalzburg/workflows/.github/workflows/qa-npm-package.yml@main

  pre-release:
    if: github.ref_name == github.event.repository.default_branch
    name: 🔹 Publish
    needs: qa-main
    permissions:
      contents: write
      id-token: write
      packages: write
      pull-requests: read
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    uses: oliversalzburg/workflows/.github/workflows/publish-npm-package.yml@main
    with:
      is-canary: true
      publish-script: |
        yarn run build
        ./.scripts/rebuild-package-structure.sh
        cd ./dist-area/
