name: Pre-Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      wants-github-release:
        default: false
        description: Create a GitHub release?
        required: false
        type: boolean

concurrency: pre-release

jobs:
  qa:
    name: 🔹 QA
    permissions:
      contents: read
      packages: read
    uses: oliversalzburg/workflows/.github/workflows/qa-npm-package.yml@main

  pre-release:
    if: github.ref_name == github.event.repository.default_branch
    name: 🔹 Publish
    needs: qa
    permissions:
      contents: write
      id-token: write
      packages: write
      pages: write
      pull-requests: read
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    uses: oliversalzburg/workflows/.github/workflows/publish-npm-package.yml@main
    with:
      has-mkdocs: false
      has-github-pages: true
      is-canary: true
      publish-script: |
        yarn run build
        ./.scripts/rebuild-package-structure.sh
        cd ./dist-area/
      wants-github-release: ${{ inputs.wants-github-release || false }}
