name: QA

on:
  pull_request:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  qa:
    name: 🔹 QA
    permissions:
      contents: read
      packages: read
    uses: oliversalzburg/workflows/.github/workflows/qa-npm-package.yml@main

  qa-passed:
    needs:
      - qa
    name: QA Passed
    permissions:
      contents: read
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
      - name: Success
        if: ${{ success() && !(contains(needs.*.result, 'failure')) }}
        run: exit 0
