name: QA

on:
  pull_request:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  qa:
    name: 🔹 QA
    permissions:
      contents: read
      packages: read
    uses: oliversalzburg/workflows/.github/workflows/qa-npm-package.yml@main
